nginx:
    image: nginx
    volumes:
        - ./webroot:/usr/share/nginx/html

haproxy:
    image: million12/haproxy
    ports:
     - 80:80
     - 443:443
    volumes:
    - ./haproxy:/etc/haproxy:ro
    - ./letsencrypt:/etc/letsencrypt:ro

letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    volumes:
     - ./letsencrypt:/etc/letsencrypt
     - ./varlibletsencrypt:/var/lib/letsencrypt
     - ./webroot:/webroot
    command: -h
