#!/bin/bash
DOMAIN=plett.uk
LEDIR=./letsencrypt
CERTDIR=$LEDIR/live/$DOMAIN
DHPARAMS=$LEDIR/$DOMAIN-dhparams.pem
if [ -z "$DHPARAMS" ]; then
	openssl dhparam -out $DHPARAMS 2048
fi
docker-compose run letsencrypt --renew-by-default certonly --webroot -w /webroot -d $DOMAIN
cat $CERTDIR/cert.pem $CERTDIR/chain.pem $CERTDIR/privkey.pem $DHPARAMS > $CERTDIR/combined.pem

# verify new expiry date with:
# echo -n|openssl s_client -connect plett.uk:443 2>/dev/null|openssl x509 -noout -dates

